version: '3.8'
services:
  go-backend:
    build: .
    container_name: hackathon-go
    expose:
      - "8081"
    networks:
      - default
      - infra-net

networks:
  infra-net:
    external: true
    name: hackathon_hackathon-net
