spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/hackathon_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

rsa:
  public-key: classpath:token/public.pem
  private-key: classpath:token/private.pem