version: '3.8'
services:
  ml-service:
    build: .
    container_name: hackathon-ml
    expose:
      - "8083"
    networks:
      - default
      - infra-net

networks:
  infra-net:
    external: true
    name: hackathon_hackathon-net
