version: '3.8'
services:
  java-backend:
    build: .
    container_name: hackathon-java
    expose:
      - "8080"
    networks:
      - default
      - infra-net

networks:
  infra-net:
    external: true
    name: hackathon_hackathon-net
