version: '3.8'
services:
  frontend:
    build: .
    container_name: hackathon-frontend
    expose:
      - "8082"
    networks:
      - default
      - infra-net

networks:
  infra-net:
    external: true
    name: hackathon_hackathon-net
